name: cli

on: [push, pull_request]

env:
  my_var: 12

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install numpy
          echo "numpy is installed"
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
            
          fi

      - name: Linting
        run: |
          pip install flake8
          flake8 app.py
